### ISSUE TITLE
This master does not have id 0x55b0 in its schema

### ISSUE THREAD

**Issue by BilalAsif25** [matthewn4444/EBMLReader#2]
@matthewn4444  Thanks for this library,

But on some videos with subtitles, its giving me this error exception while reading. how to overcome it ?

com.matthewn4444.ebml.EBMLParsingException: This master does not have id 0x55b0 in its schema
2020-07-29 11:46:29.257 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.readSection(MasterElement.java:442)
2020-07-29 11:46:29.258 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.read(MasterElement.java:116)
2020-07-29 11:46:29.258 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.readSection(MasterElement.java:394)
2020-07-29 11:46:29.259 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.read(MasterElement.java:116)
2020-07-29 11:46:29.260 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.readSection(MasterElement.java:394)
2020-07-29 11:46:29.261 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.parse(MasterElement.java:102)
2020-07-29 11:46:29.263 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.elements.MasterElement.parse(MasterElement.java:92)
2020-07-29 11:46:29.264 31117-32464/com.bpva.video.player.free W/System.err:     at com.matthewn4444.ebml.EBMLReader.readTracks(EBMLReader.java:362)

**Comment by matthewn4444** [comment]
Sorry I haven't been maintaining this, looks like that is color entry. I may add it eventually.

**Comment by matthewn4444** [comment]
Do you have a sample file with this because Color is a master element and it has a lot of nodes to add (find Color https://www.matroska.org/technical/elements.html)

**Comment by matthewn4444** [comment]
Actually if that node is not important I could try add a mode to bypass all unsupported nodes instead of throwing

**Comment by matthewn4444** [comment]
For now I am going to close, if you need this field you can reopen, otherwise my newest change ignores unreadable labels.
